---
name: CI

on: [push, pull_request]

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        python-version: '3.x'
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install setuptools wheel twine
      - name: Build packages
        run: |
          python utils/build-dists.py
      - name: Check packages
        run: |
          set -exo pipefail;
          if [ $(python -m twine check dist/* | grep -c 'warning') != 0 ]; then exit 1; fi

  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: '3.x'
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install nox
      - name: Lint the code
        run: nox --no-error-on-missing-interpreter -s lint

  test-build-distribution:
    strategy:
      fail-fast: false
      matrix:
        python-version: '3.x'
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: |
          python -m pip install --upgrade build
      - name: Build project for distribution
        run: |
          python -m build

  test-linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Set Up Python - ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: |
          python -m pip install nox
      - name: Run Tests
        run: |
          nox --no-error-on-missing-interpreter -rs lint test
